### ISSUE TITLE
Not working with ejabberd-14.07

### ISSUE THREAD

**Issue by codescrapper** [johanvorster/ejabberd_confirm_delivery#3]
Hi, I liked your idea of saving messages on server side if ack not received. 

But somehow this is not working for me. 
I generated beam file and copied it in ebin folder and restarted the server.

I started getting this error:

[{p1_logger,info_msg,
            [mod_confirm_delivery,24,"mod_confirm_delivery loading",[]],
            []},
 {mod_confirm_delivery,start,2,[{file,"mod_confirm_delivery.erl"},{line,24}]},
 {gen_mod,start_module,3,[{file,"src/gen_mod.erl"},{line,82}]},
 {lists,foreach,2,[{file,"lists.erl"},{line,1323}]},
 {ejabberd_app,start,2,[{file,"src/ejabberd_app.erl"},{line,67}]},
 {application_master,start_it_old,4,
                     [{file,"application_master.erl"},{line,269}]}]

Can you help me out here I am very new to erlang and ejabberd.

**Comment by johanvorster** [comment]
Sorry for the late reply, unfortunately I don't have the erlang/ejabberd environments at my disposal anymore. So it's not possible to check whats happening. Where are you compiling from? Try compiling it from the ebin folder.

If you do find the cause of the error, please could you let me know what it the issue was.

**Comment by johanvorster** [comment]
Here is a fork from this repository that might be more up to date

fernandogrd@0f914a9

**Comment by johanvorster** [comment]
It seems ejabberd changed INFO_MSG macro and send_packet arguments from version 13.10.

**Comment by codescrapper** [comment]
Ok the module is working now. Added erl file to src. Configured ejabberd again. 

Also you need to add this 
-include("logger.hrl").

Thanks

**Comment by ghost** [comment]
Hi @codescrapper Could i have a look at the changes you made.
I can't locate to which src you have added the file.
PS: I am working with version 14.07 as well.

Thanks!
