### ISSUE TITLE
ejabberd_confirm_delivery for ejabberd 14.12

### ISSUE THREAD

**Issue by pitbeta86** [johanvorster/ejabberd_confirm_delivery#6]
I am using ejabberd 14.12.

I compile the module then add the module in yml file and restart the ejabberd.

No errors were showing in the log files.

But when i test it no offline messages were storing in the mnesia "offline_msg" table?

**Comment by johanvorster** [comment]
Has the offline_msg table been created? Check if it exist. This was tested with Mnesia.

Also, it will only populate if the client isn't online.

Have you enabled xep-0184?

Good thing to do is have the logging verbose, so you can see all the debug messages. This might indicate what the work flow is.

**Comment by pitbeta86** [comment]
Yes the offline_msg table already there in the Mnesia database.

I checked the log and found that inside user_send_packet hook the "Type","Body"and "Sessions"
were showing null.
So i changed the code and now i am getting Type and Body but still not getting the Sessions.
This is the code
"Sessions = mnesia:dirty_index_read(session, {LUser, LServer}, #session.us),"
Therefore i couldn't get inside "case" expression.

Can you help me with this?

**Comment by johanvorster** [comment]
Are you using "chat" types for the Stanza's?
If you're getting the From, To and Packet, I suppose you don't really need the session info.

try removing Session in the case statement and see if it does what you want.

**Comment by pitbeta86** [comment]
Yes i remove the Session and data is showing in mnesia "offline_msg" table.

But it showing duplicate message .I think it need to be handeled in clientside right?

And the offline message is not showing after i come back online as i think i am using odbc for my offline table.

So can you help me how to insert offline message to spool table in this module?

**Comment by johanvorster** [comment]
Yes, so the client need to handle duplication, as it's a possibility to get.

The client should automatically look for offline messages. Is it only this Modules offline message that aren't coming through? Or all offline messages?

I used mnesia, so can't comment on odbc.

**Comment by johanvorster** [comment]
Also, have you had a look at the Forks of this repo? Some of the other contributes might have had the same problems.

**Comment by pitbeta86** [comment]
Thank you for your reply 

It is working now.

I inserted offline message to mysql and now i can see the message.

**Comment by johanvorster** [comment]
brilliant!! Might be worth creating your own fork on this repo and commit your implementation to GitHub. So other with the same problem can use your code.

**Comment by pitbeta86** [comment]
Hello the mod_confirm_delivery is working properly for 1-1 chat .

But it is not working for MUC(Offline group chat) messages.

So can anyone help me with this?
